// Sample REQUEST transformer script.
// Modified from version originally generated by Claude.
// For learning purposes only.

(function(inputs) {
    /* inputs structure: {
        prompt_data: object,
        request_data: object
    } */
    var requestData = inputs.request_data;
    var promptData = inputs.prompt_data;
    var prompt = promptData.prompt;
    var model = promptData.model;

    // Output the inputs object to the system log for inspection
    // gs.info('LLM Transformer inputs: ' + JSON.stringify(inputs));

    // Gemini API body, as per the Gemini Interactions API (POST /v1beta/interactions)
    var body = {
        model: model,
        input: prompt,
        generation_config: {
            temperature: parseFloat(promptData.temperature),
            max_output_tokens: parseInt(promptData.max_tokens)
        },
        stream: false
    };

    // Specify Api-Revision
    var headers = {
		"Api-Revision": "2026-05-20"
	};

    return {
        body: body,
        headers: headers
    };
})(inputs);

/* ----------------------------------------------------*/

// Sample RESPONSE transformer script.
// Modified from version originally generated by Claude.
// For learning purposes only.

(function(inputs) {
    /* inputs structure: {
        prompt_data: object,
        request_data: object,
        response_body: string,
        response_headers: string
    } */
    var requestData = inputs.request_data;
    var promptData = inputs.prompt_data;
    var responseBody = JSON.parse(inputs.response_body);
    // gs.info("Gemini response: " + inputs.response_body);
    var responseTexts = [];

    // Current Interactions API schema returns a "steps" array (the old flat
    // "outputs" array was fully retired June 6, 2026). Pull text out of any
    // model_output step's content blocks.
    var steps = responseBody.steps || [];
    for (var i = 0; i < steps.length; i++) {
        var step = steps[i];
        if (step.type === "model_output" && step.content) {
            for (var j = 0; j < step.content.length; j++) {
                if (step.content[j].type === "text") {
                    responseTexts.push(step.content[j].text);
                }
            }
        }
    }

    if (responseTexts.length === 0) {
        gs.info("Gemini transformer: no model_output text found, response status: " + responseBody.status);
    }

    return responseTexts;
})(inputs);